kind: pipeline
type: docker
name: web

steps:
  - name: npm install # name 不能重复
    image: node:16 # 使⽤的镜像
    commands:
      - npm i --registry=https://registry.npm.taobao.org # 更改源地址

  - name: test
    image: node:16
    commands:
      - npm run test

#  node 执行版本在image  node:16  or node:lasted
  - name: build
    image: node:16
    commands:
      - npm run build

  - name: rsync
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
    settings:
      hosts:
        - 47.95.109.212
      source: .vuepress/dist/*
      target: /root/doc
      secrets: [ rsync_key ]


   - name: notify
    image: curlimages/curl
    commands:
      - |
      curl -H "Content-Type:application/json" -X POST -d '{"text": {"content":"部署成功"},msgtype:"text"}' 'https://oapi.dingtalk.com/robot/send?access_token=587d203031917523bc857f011a052ba3f2044e37be49a878b5ae39d505c9ba01'
