kind: pipeline
type: docker
name: web

steps:
- name: version
  image: node:alpine
  commands:
  - npm -v
  

- name: npm install # name 不能重复
  image: node:alpine # 使⽤的镜像
  commands:
  - npm i --registry=https://registry.npm.taobao.org # 更改源地址

- name: test
  image: node:alpine
  commands:
  - npm run test

- name: build
  image: node:alpine
  commands:
    - npm run build

- name: rsync
  image: drillster/drone-rsync
  settings:
    user: some-user
    key:
      from_secret: rsync_key
    hosts:
      - 47.95.109.212
    source: .vuepress/dist/*
    target: /root/doc
    secrets: [ rsync_key ]