kind: pipeline
type: docker
name: web

steps:
  - name: npm install # name 不能重复
    image: node:16 # 使⽤的镜像
    commands:
      - npm i --registry=https://registry.npm.taobao.org # 更改源地址

  - name: test
    image: node:16
    commands:
      - npm run test

  - name: build
    image: node:16
    commands:
      - npm run build
